; Listing generated by Microsoft (R) Optimizing Compiler Version 15.00.30729.01 

	TITLE	c:\Users\Admin\Desktop\Projects\SEye_Server\engine_threading.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB OLDNAMES

PUBLIC	?CriticalLock@@3PAXA				; CriticalLock
?CriticalLock@@3PAXA DD 01H DUP (?)			; CriticalLock
PUBLIC	?InitEngineThreading@@YAXI@Z			; InitEngineThreading
; Function compile flags: /Ogtpy
; File c:\users\admin\desktop\projects\seye_server\engine_threading.cpp
;	COMDAT ?InitEngineThreading@@YAXI@Z
_TEXT	SEGMENT
?InitEngineThreading@@YAXI@Z PROC			; InitEngineThreading, COMDAT

; 21   : 	switch(exe)

	mov	eax, 1
	cmp	eax, DWORD PTR ?Exe@@3HA		; Exe
	sbb	ecx, ecx
	and	ecx, -4205216				; ffbfd560H
	add	ecx, 4205216				; 00402aa0H
	mov	DWORD PTR ?CriticalLock@@3PAXA, ecx	; CriticalLock

; 22   : 	{
; 23   : 		case 0: //game.exe
; 24   : 		case 1: //server.dat
; 25   : 			CriticalLock =	(void *)0x00402AA0;
; 26   : 			break;
; 27   : 		default: //RH7/RH8/LevelEdit
; 28   : 			CriticalLock = (void *)0;
; 29   : 			break;
; 30   : 	}
; 31   : }

	ret	0
?InitEngineThreading@@YAXI@Z ENDP			; InitEngineThreading
END
