; Listing generated by Microsoft (R) Optimizing Compiler Version 15.00.30729.01 

	TITLE	c:\Users\Admin\Desktop\Projects\SEye_Server\gmmain.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB OLDNAMES

PUBLIC	?Settings@@3PAUSettingsStruct@@A		; Settings
PUBLIC	?Data@@3PAUDataStruct@@A			; Data
?Settings@@3PAUSettingsStruct@@A DD 01H DUP (?)		; Settings
?Data@@3PAUDataStruct@@A DD 01H DUP (?)			; Data
__bad_alloc_Message DD FLAT:??_C@_0P@GHFPNOJB@bad?5allocation?$AA@
END
