; Listing generated by Microsoft (R) Optimizing Compiler Version 15.00.30729.01 

	TITLE	c:\Users\Admin\Desktop\Projects\SEye_Server\engine_tdb.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB OLDNAMES

PUBLIC	?Get_TDB_Object@@3P6APAVTDBObjClass@@K@ZA	; Get_TDB_Object
PUBLIC	?Get_VehicleName@@3P6APA_WXZA			; Get_VehicleName
PUBLIC	??_C@_07GJJCKENN@Neutral?$AA@			; `string'
PUBLIC	??_C@_1BA@KOPEKOGK@?$AAV?$AAe?$AAh?$AAi?$AAc?$AAl?$AAe?$AA?$AA@ ; `string'
?Get_TDB_Object@@3P6APAVTDBObjClass@@K@ZA DD 01H DUP (?) ; Get_TDB_Object
?Get_VehicleName@@3P6APA_WXZA DD 01H DUP (?)		; Get_VehicleName
;	COMDAT ??_C@_1BA@KOPEKOGK@?$AAV?$AAe?$AAh?$AAi?$AAc?$AAl?$AAe?$AA?$AA@
CONST	SEGMENT
??_C@_1BA@KOPEKOGK@?$AAV?$AAe?$AAh?$AAi?$AAc?$AAl?$AAe?$AA?$AA@ DB 'V', 00H
	DB	'e', 00H, 'h', 00H, 'i', 00H, 'c', 00H, 'l', 00H, 'e', 00H, 00H
	DB	00H						; `string'
CONST	ENDS
;	COMDAT ??_C@_07GJJCKENN@Neutral?$AA@
CONST	SEGMENT
??_C@_07GJJCKENN@Neutral?$AA@ DB 'Neutral', 00H		; `string'
PUBLIC	?InitEngineTDB@@YAXI@Z				; InitEngineTDB
; Function compile flags: /Ogtpy
; File c:\users\admin\desktop\projects\seye_server\engine_tdb.cpp
;	COMDAT ?InitEngineTDB@@YAXI@Z
_TEXT	SEGMENT
?InitEngineTDB@@YAXI@Z PROC				; InitEngineTDB, COMDAT

; 39   : {

	mov	eax, DWORD PTR ?Exe@@3HA		; Exe

; 40   : 	switch(exe)

	cmp	eax, 3
	ja	SHORT $LN1@InitEngine@2
	jmp	DWORD PTR $LN10@InitEngine@2[eax*4]
$LN5@InitEngine@2:

; 41   : 	{
; 42   : 		case 0: //game.exe
; 43   : 			Get_TDB_Object = (GetTDBObject)0x0076C5B0;

	mov	DWORD PTR ?Get_TDB_Object@@3P6APAVTDBObjClass@@K@ZA, 7783856 ; Get_TDB_Object, 0076c5b0H

; 44   : 			Get_VehicleName = (GetVehicleName)0x0067C740;

	mov	DWORD PTR ?Get_VehicleName@@3P6APA_WXZA, 6801216 ; Get_VehicleName, 0067c740H

; 61   : 			break;
; 62   : 	}
; 63   : }

	ret	0
$LN4@InitEngine@2:

; 45   : 			break;
; 46   : 		case 1: //server.dat
; 47   : 			Get_TDB_Object = (GetTDBObject)0x0076BE50;

	mov	DWORD PTR ?Get_TDB_Object@@3P6APAVTDBObjClass@@K@ZA, 7781968 ; Get_TDB_Object, 0076be50H

; 48   : 			Get_VehicleName = (GetVehicleName)0x0067BFE0;

	mov	DWORD PTR ?Get_VehicleName@@3P6APA_WXZA, 6799328 ; Get_VehicleName, 0067bfe0H

; 61   : 			break;
; 62   : 	}
; 63   : }

	ret	0
$LN3@InitEngine@2:

; 49   : 			break;
; 50   : 		case 2: //RH73
; 51   : 			Get_TDB_Object = (GetTDBObject)0x08346D80;

	mov	DWORD PTR ?Get_TDB_Object@@3P6APAVTDBObjClass@@K@ZA, 137653632 ; Get_TDB_Object, 08346d80H

; 52   : 			Get_VehicleName = (GetVehicleName)0x08188FD0;

	mov	DWORD PTR ?Get_VehicleName@@3P6APA_WXZA, 135827408 ; Get_VehicleName, 08188fd0H

; 61   : 			break;
; 62   : 	}
; 63   : }

	ret	0
$LN2@InitEngine@2:

; 53   : 			break;
; 54   : 		case 3: //RH8
; 55   : 			Get_TDB_Object = (GetTDBObject)0x082FBF90;

	mov	DWORD PTR ?Get_TDB_Object@@3P6APAVTDBObjClass@@K@ZA, 137346960 ; Get_TDB_Object, 082fbf90H

; 56   : 			Get_VehicleName = (GetVehicleName)0x08172B74;

	mov	DWORD PTR ?Get_VehicleName@@3P6APA_WXZA, 135736180 ; Get_VehicleName, 08172b74H

; 61   : 			break;
; 62   : 	}
; 63   : }

	ret	0
$LN1@InitEngine@2:

; 57   : 			break;
; 58   : 		default:
; 59   : 			Get_TDB_Object = (GetTDBObject)0;

	xor	eax, eax
	mov	DWORD PTR ?Get_TDB_Object@@3P6APAVTDBObjClass@@K@ZA, eax ; Get_TDB_Object

; 60   : 			Get_VehicleName = (GetVehicleName)0;

	mov	DWORD PTR ?Get_VehicleName@@3P6APA_WXZA, eax ; Get_VehicleName

; 61   : 			break;
; 62   : 	}
; 63   : }

	ret	0
	npad	2
$LN10@InitEngine@2:
	DD	$LN5@InitEngine@2
	DD	$LN4@InitEngine@2
	DD	$LN3@InitEngine@2
	DD	$LN2@InitEngine@2
?InitEngineTDB@@YAXI@Z ENDP				; InitEngineTDB
END
