; Listing generated by Microsoft (R) Optimizing Compiler Version 15.00.30729.01 

	TITLE	c:\Users\Admin\Desktop\Projects\SEye_Server\engine_pt.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB OLDNAMES

PUBLIC	?Peek_Buffer@StringClass@@QAEPADXZ		; StringClass::Peek_Buffer
PUBLIC	?Find_Purchase_Definition@@3PAXA		; Find_Purchase_Definition
PUBLIC	?Find_Team_Purchase_Definition@@3PAXA		; Find_Team_Purchase_Definition
PUBLIC	?DefinitionArray@@3PAPAVPurchaseSettingsDefClass@@A ; DefinitionArray
?Find_Purchase_Definition@@3PAXA DD 01H DUP (?)		; Find_Purchase_Definition
?Find_Team_Purchase_Definition@@3PAXA DD 01H DUP (?)	; Find_Team_Purchase_Definition
?DefinitionArray@@3PAPAVPurchaseSettingsDefClass@@A DD 01H DUP (?) ; DefinitionArray
PUBLIC	?InitEnginePT@@YAXI@Z				; InitEnginePT
; Function compile flags: /Ogtpy
; File c:\users\admin\desktop\projects\seye_server\engine_pt.cpp
;	COMDAT ?InitEnginePT@@YAXI@Z
_TEXT	SEGMENT
?InitEnginePT@@YAXI@Z PROC				; InitEnginePT, COMDAT

; 36   : {

	mov	eax, DWORD PTR ?Exe@@3HA		; Exe

; 37   : 	switch(exe)

	cmp	eax, 3
	ja	$LN1@InitEngine@4
	jmp	DWORD PTR $LN10@InitEngine@4[eax*4]
$LN5@InitEngine@4:

; 38   : 	{
; 39   : 		case 0: //game.exe
; 40   : 			DefinitionArray = (PurchaseSettingsDefClass **)0x0085E180;

	mov	DWORD PTR ?DefinitionArray@@3PAPAVPurchaseSettingsDefClass@@A, 8774016 ; DefinitionArray, 0085e180H

; 41   : 			Find_Purchase_Definition = (void *)0x006F2BD0;

	mov	DWORD PTR ?Find_Purchase_Definition@@3PAXA, 7285712 ; Find_Purchase_Definition, 006f2bd0H

; 42   : 			Find_Team_Purchase_Definition = (void *)0x006F3430;

	mov	DWORD PTR ?Find_Team_Purchase_Definition@@3PAXA, 7287856 ; Find_Team_Purchase_Definition, 006f3430H

; 63   : 			break;
; 64   : 	}
; 65   : }

	ret	0
$LN4@InitEngine@4:

; 43   : 			break;
; 44   : 		case 1: //server.dat
; 45   : 			DefinitionArray = (PurchaseSettingsDefClass **)0x0085D358;

	mov	DWORD PTR ?DefinitionArray@@3PAPAVPurchaseSettingsDefClass@@A, 8770392 ; DefinitionArray, 0085d358H

; 46   : 			Find_Purchase_Definition = (void *)0x006F2190;

	mov	DWORD PTR ?Find_Purchase_Definition@@3PAXA, 7283088 ; Find_Purchase_Definition, 006f2190H

; 47   : 			Find_Team_Purchase_Definition = (void *)0x006F29F0;

	mov	DWORD PTR ?Find_Team_Purchase_Definition@@3PAXA, 7285232 ; Find_Team_Purchase_Definition, 006f29f0H

; 63   : 			break;
; 64   : 	}
; 65   : }

	ret	0
$LN3@InitEngine@4:

; 48   : 			break;
; 49   : 		case 2: //RH73
; 50   : 			DefinitionArray = (PurchaseSettingsDefClass **)0x086CA920;

	mov	DWORD PTR ?DefinitionArray@@3PAPAVPurchaseSettingsDefClass@@A, 141338912 ; DefinitionArray, 086ca920H

; 51   : 			Find_Purchase_Definition = (void *)0x08146D08;

	mov	DWORD PTR ?Find_Purchase_Definition@@3PAXA, 135556360 ; Find_Purchase_Definition, 08146d08H

; 52   : 			Find_Team_Purchase_Definition = (void *)0x0817A6D4;

	mov	DWORD PTR ?Find_Team_Purchase_Definition@@3PAXA, 135767764 ; Find_Team_Purchase_Definition, 0817a6d4H

; 63   : 			break;
; 64   : 	}
; 65   : }

	ret	0
$LN2@InitEngine@4:

; 53   : 			break;
; 54   : 		case 3: //RH8
; 55   : 			DefinitionArray = (PurchaseSettingsDefClass **)0x085F2180;

	mov	DWORD PTR ?DefinitionArray@@3PAPAVPurchaseSettingsDefClass@@A, 140452224 ; DefinitionArray, 085f2180H

; 56   : 			Find_Purchase_Definition = (void *)0x08135F3A;

	mov	DWORD PTR ?Find_Purchase_Definition@@3PAXA, 135487290 ; Find_Purchase_Definition, 08135f3aH

; 57   : 			Find_Team_Purchase_Definition = (void *)0x081658D6;

	mov	DWORD PTR ?Find_Team_Purchase_Definition@@3PAXA, 135682262 ; Find_Team_Purchase_Definition, 081658d6H

; 63   : 			break;
; 64   : 	}
; 65   : }

	ret	0
$LN1@InitEngine@4:

; 58   : 			break;
; 59   : 		default:
; 60   : 			DefinitionArray = (PurchaseSettingsDefClass **)0;

	xor	eax, eax
	mov	DWORD PTR ?DefinitionArray@@3PAPAVPurchaseSettingsDefClass@@A, eax ; DefinitionArray

; 61   : 			Find_Purchase_Definition = (void *)0;

	mov	DWORD PTR ?Find_Purchase_Definition@@3PAXA, eax ; Find_Purchase_Definition

; 62   : 			Find_Team_Purchase_Definition = (void *)0;

	mov	DWORD PTR ?Find_Team_Purchase_Definition@@3PAXA, eax ; Find_Team_Purchase_Definition

; 63   : 			break;
; 64   : 	}
; 65   : }

	ret	0
	npad	1
$LN10@InitEngine@4:
	DD	$LN5@InitEngine@4
	DD	$LN4@InitEngine@4
	DD	$LN3@InitEngine@4
	DD	$LN2@InitEngine@4
?InitEnginePT@@YAXI@Z ENDP				; InitEnginePT
END
